### PR TITLE
header name case-insenstive as defined in RFC-2616

### LINKED ISSUE #5: Regular expression for location-header should be case-insensitve
RFC-2616 part 4.2 defines http-message-header-names as case-insensitive.
currently the regular expressions are case-sensitive.

depending on the server-implementation some 301/302 redirects fails. here an example with phpbrew:

```bash
===> phpbrew will now build 7.3.4
===> Loading and resolving variants...
Checking distribution checksum...
Checksum mismatch: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 != 2e2c3d8212c83649e443b61efffbd03df4b9edd0f9c7a679081fe4cb2da12b78
Re-Downloading...
Downloading http://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror via curl extension
[==================================================================] 185.00/185.00B 100%
Redirecting to https://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror
CurlKit\CurlException:  at [The Location header can not be found: HTTP/2 302 
server: myracloud
date: Mon, 08 Apr 2019 10:05:14 GMT
content-type: text/html; charset=utf-8
content-language: en
x-frame-options: SAMEORIGIN
set-cookie: COUNTRY=NA%2C217.91.159.15; expires=Mon, 15-Apr-2019 10:05:14 GMT; Max-Age=604800; path=/; domain=.php.net
x-php-load: 0.51, 0.64, 0.46
status: 302 Found
location: https://www.php.net/distributions/php-7.3.4.tar.bz2
strict-transport-security: max-age=31536000
expires: Mon, 08 Apr 2019 10:05:14 GMT
cache-control: max-age=0]

```

### PR DESCRIPTION
**Pull request by jochen42**
fixes #5

### CODE REVIEW

**Comment by jochen42** [comment]
@c9s, thanks for merging! are you planing to create an packagist-release?

**Comment by c9s** [comment]
Sure I can create a new release for it

jochen <notifications@github.com>於 2019年4月8日 週一，21:14寫道：

**Comment by c9s** [comment]
@jochen42   1.0.10 is released

**Comment by morozov** [comment]
@c9s, for some reason, the [1.0.10](https://github.com/c9s/CurlKit/releases/tag/1.0.10) release is unavailable on Packagist (the last one is 1.0.9). You'll probably need to log into Packagist using your GitHub account in order to let it update the needed GitHub hooks.

**Comment by c9s** [comment]
I already clicked the update button, but 1.0.10 didn’t come out.

Sergei Morozov <notifications@github.com>於 2019年11月30日 週六，05:14寫道：

**Comment by morozov** [comment]
Could you check out the [GitHub Hook](https://packagist.org/about#how-to-update-packages) setup instructions or follow up with the Packagist support if it doesn't work?

Since you're the account owner, you're the only one who can do that.

Thank you.

**Comment by c9s** [comment]
let me check

Sergei Morozov <notifications@github.com>於 2019年11月30日 週六，08:43寫道：

**Comment by morozov** [comment]
@c9s, as a project member, I still cannot manage webhooks. You'll have to do it yourself using the instructions I posted earlier.

**Comment by c9s** [comment]
I have already checked the webhook configuration and everything looks fine,
the payload response 200ok.

It must be something wrong with the composer config. Manually update
doesn’t work as well.

Sergei Morozov <notifications@github.com>於 2019年12月1日 週日，04:30寫道：

**Comment by morozov** [comment]
It was because of the [version specified in composer.json](https://medium.com/packagist/tagged-a-new-release-for-composer-and-it-wont-show-up-on-packagist-org-or-on-private-packagist-efaf21c212ff) (removed in https://github.com/c9s/CurlKit/commit/5f0765bd6e81d66ec6f71d24c6312a1509e65c5f). After that, the [new release is available](https://packagist.org/packages/corneltek/curlkit#1.0.11) on Packagist.

**Pull request merged**
